# -*- coding: utf-8 -*-
"""Analysis-of-Global-GDP-and-Population-Trends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMz6psdniV5684nNHqmjdbll6TGME09E
"""

# Basic libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Make plots look nice
plt.style.use('seaborn-v0_8')

# Load data
df = pd.read_csv('countrydata.csv')

# Quick look
df.head()

# Select only the columns we actually need
data = df[['regionname', 'countryname', 'gdp_ff_bf', 'population']].copy()

# Drop rows that have missing GDP or population values
data = data.dropna(subset=['gdp_ff_bf', 'population'])

# Rename columns to easier names
data = data.rename(columns={'regionname': 'Region',
                            'countryname': 'Country',
                            'gdp_ff_bf': 'GDP',
                            'population': 'Population'})

# Check the cleaned data
data.head()

plt.figure(figsize=(8,6))
sns.scatterplot(data=data, x='Population', y='GDP', hue='Region', s=80)

# 🔹 Bold and clear text formatting
plt.title('GDP vs Population by Region', fontsize=14, fontweight='bold')
plt.xlabel('Population', fontsize=12, fontweight='bold')
plt.ylabel('GDP per Capita', fontsize=12, fontweight='bold')

# 🔹 Improve tick label visibility
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)

# Optional: move legend to a clear spot
plt.legend(title='Region', title_fontsize=11, fontsize=9, loc='best')

plt.show()

plt.figure(figsize=(8,6))
sns.barplot(data=data, x='Region', y='GDP', estimator=np.mean, ci=None)

# 🔹 Bold title and labels
plt.title('Average GDP per Region', fontsize=14, fontweight='bold')
plt.xlabel('Region', fontsize=12, fontweight='bold')
plt.ylabel('Average GDP', fontsize=12, fontweight='bold')

# 🔹 Better readability for tick labels
plt.xticks(rotation=45, fontsize=10)
plt.yticks(fontsize=10)

plt.show()

plt.figure(figsize=(8,6))
sns.boxplot(data=data, x='Region', y='GDP')

# 🔹 Bold title and axis labels
plt.title('GDP Distribution by Region', fontsize=14, fontweight='bold')
plt.xlabel('Region', fontsize=12, fontweight='bold')
plt.ylabel('GDP', fontsize=12, fontweight='bold')

# 🔹 Rotate x-axis labels for clarity and make ticks readable
plt.xticks(rotation=45, fontsize=10)
plt.yticks(fontsize=10)

plt.show()

# 🔹 Correlation Heatmap (Optional Extra Plot)
plt.figure(figsize=(6,4))
sns.heatmap(data[['GDP', 'Population']].corr(), annot=True, cmap='Blues', fmt=".2f")

# 🔹 Bold title and labels
plt.title('Correlation between GDP and Population', fontsize=14, fontweight='bold')

# 🔹 Make axis tick labels bold and readable
plt.xticks(fontsize=11, fontweight='bold')
plt.yticks(fontsize=11, fontweight='bold', rotation=0)

plt.show()

from scipy.stats import skew, kurtosis

mean_gdp = data['GDP'].mean()
variance_gdp = data['GDP'].var()
skewness_gdp = skew(data['GDP'])
kurtosis_gdp = kurtosis(data['GDP'])

print("Mean GDP:", mean_gdp)
print("Variance:", variance_gdp)
print("Skewness:", skewness_gdp)
print("Kurtosis:", kurtosis_gdp)



